DROP TABLE IF EXISTS TB_TRANSACTION;
 
CREATE TABLE TB_TRANSACTION (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  TRANSACTION_DATE DATE NOT NULL,
  VENDOR VARCHAR(250) NOT NULL,
  TRANSACTION_TYPE VARCHAR(50) NOT NULL,
  AMOUNT DOUBLE NOT NULL,
  CATEGORY VARCHAR(100) NULL
);